import type { Question } from './types';
import Counter from './solutions/Counter';
import TodoApp from './solutions/TodoApp';
import DebouncedSearch from './solutions/DebouncedSearch';
import Accordian from './solutions/Accordian';
import StaleClosureExample from './solutions/StaleClouserExample';
import ContactForm from './solutions/ContactForm';
import InfiniteScroll from './solutions/InfiniteScroll';

// Placeholder component for questions not yet implemented
// eslint-disable-next-line react-refresh/only-export-components
const Placeholder = () => (
  <div className="flex items-center justify-center min-h-[400px]">
    <div className="text-center">
      <p className="text-gray-500 dark:text-gray-400 mb-2">Solution coming soon...</p>
      <p className="text-sm text-gray-400 dark:text-gray-500">
        Implement this component in features/machineCoding/solutions/
      </p>
    </div>
  </div>
);

export const questions: Question[] = [
  // Core React (Most Asked)
  {
    id: 'counter',
    title: 'Counter with increment/decrement',
    description: 'Build a counter component with increment, decrement, and reset functionality',
    type: 'react',
    category: 'core',
    difficulty: 'easy',
    component: Counter,
  },
  {
    id: 'todo-app',
    title: 'Todo App (CRUD)',
    description: 'Create a todo application with create, read, update, and delete operations',
    type: 'react',
    category: 'core',
    difficulty: 'medium',
    component: TodoApp,
  },
  {
    id: 'debounced-search',
    title: 'Debounced search input',
    description: 'Implement a search input with debouncing to optimize API calls',
    type: 'react',
    category: 'core',
    difficulty: 'medium',
    component: DebouncedSearch,
  },
  {
    id: 'stale-closure',
    title: 'Stale Closure Example',
    description: 'Demonstrate the stale closure problem in React and how to fix it',
    type: 'react',
    category: 'core',
    difficulty: 'easy',
    component: StaleClosureExample,
  },
  {
    id: 'contact-form',
    title: 'Contact Form',
    description: 'Create a contact form with name, email, and message fields',
    type: 'react',
    category: 'core',
    difficulty: 'medium',
    component: ContactForm,
  },
  {
    id: 'modal',
    title: 'Modal component',
    description: 'Build a reusable modal component with overlay and close functionality',
    type: 'react',
    category: 'core',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'tabs',
    title: 'Tabs component',
    description: 'Create a tabs component with keyboard navigation',
    type: 'react',
    category: 'core',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'accordion',
    title: 'Accordion',
    description: 'Build an accordion component with expand/collapse functionality',
    type: 'react',
    category: 'core',
    difficulty: 'easy',
    component: Accordian,
  },
  {
    id: 'pagination',
    title: 'Pagination',
    description: 'Implement pagination with page numbers and navigation',
    type: 'react',
    category: 'core',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'infinite-scroll',
    title: 'Infinite scroll',
    description: 'Create an infinite scroll list with loading states',
    type: 'react',
    category: 'core',
    difficulty: 'hard',
    component: InfiniteScroll,
  },
  {
    id: 'dropdown-keyboard',
    title: 'Dropdown with keyboard navigation',
    description: 'Build a dropdown with arrow key navigation and selection',
    type: 'react',
    category: 'core',
    difficulty: 'hard',
    component: Placeholder,
  },

  // State & Hooks
  {
    id: 'use-debounce',
    title: 'useDebounce hook',
    description: 'Create a custom useDebounce hook',
    type: 'react',
    category: 'state',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'use-throttle',
    title: 'useThrottle hook',
    description: 'Create a custom useThrottle hook',
    type: 'react',
    category: 'state',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'use-previous',
    title: 'usePrevious hook',
    description: 'Create a custom usePrevious hook to track previous values',
    type: 'react',
    category: 'state',
    difficulty: 'easy',
    component: Placeholder,
  },
  {
    id: 'use-outside-click',
    title: 'useOutsideClick',
    description: 'Create a hook to detect clicks outside an element',
    type: 'react',
    category: 'state',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'custom-form-validation',
    title: 'Custom form validation hook',
    description: 'Build a reusable form validation hook',
    type: 'react',
    category: 'state',
    difficulty: 'hard',
    component: Placeholder,
  },

  // Performance
  {
    id: 'virtualized-list',
    title: 'Virtualized list',
    description: 'Implement a virtualized list for large datasets',
    type: 'react',
    category: 'performance',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'memoized-list',
    title: 'Memoized list rendering',
    description: 'Optimize list rendering with React.memo and useMemo',
    type: 'react',
    category: 'performance',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'optimized-search-filter',
    title: 'Optimized search filter',
    description: 'Create an optimized search filter with memoization',
    type: 'react',
    category: 'performance',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'image-lazy-loading',
    title: 'Image lazy loading',
    description: 'Implement lazy loading for images using Intersection Observer',
    type: 'react',
    category: 'performance',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'window-resize-optimization',
    title: 'Window resize listener optimization',
    description: 'Optimize window resize listeners with throttling',
    type: 'react',
    category: 'performance',
    difficulty: 'medium',
    component: Placeholder,
  },

  // UI / UX
  {
    id: 'toast-notifications',
    title: 'Toast notification system',
    description: 'Build a toast notification system with queue management',
    type: 'react',
    category: 'ui',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'theme-switcher',
    title: 'Theme switcher',
    description: 'Create a theme switcher with persistence',
    type: 'react',
    category: 'ui',
    difficulty: 'easy',
    component: Placeholder,
  },
  {
    id: 'skeleton-loader',
    title: 'Skeleton loader',
    description: 'Build skeleton loading components',
    type: 'react',
    category: 'ui',
    difficulty: 'easy',
    component: Placeholder,
  },
  {
    id: 'stepper',
    title: 'Stepper component',
    description: 'Create a multi-step stepper component',
    type: 'react',
    category: 'ui',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'carousel',
    title: 'Carousel / slider',
    description: 'Build a carousel component with autoplay and navigation',
    type: 'react',
    category: 'ui',
    difficulty: 'hard',
    component: Placeholder,
  },

  // Data Handling
  {
    id: 'table-sorting',
    title: 'Table with sorting',
    description: 'Create a table with sortable columns',
    type: 'react',
    category: 'data',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'table-filtering',
    title: 'Table with filtering',
    description: 'Build a table with column filtering',
    type: 'react',
    category: 'data',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'table-pagination',
    title: 'Table with pagination',
    description: 'Implement a table with pagination controls',
    type: 'react',
    category: 'data',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'searchable-dropdown',
    title: 'Searchable dropdown',
    description: 'Create a dropdown with search functionality',
    type: 'react',
    category: 'data',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'multi-select-dropdown',
    title: 'Multi-select dropdown',
    description: 'Build a multi-select dropdown component',
    type: 'react',
    category: 'data',
    difficulty: 'hard',
    component: Placeholder,
  },

  // Advanced
  {
    id: 'file-upload',
    title: 'File upload with preview',
    description: 'Create a file upload component with image preview',
    type: 'react',
    category: 'advanced',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'drag-drop-list',
    title: 'Drag and drop list',
    description: 'Implement a draggable and sortable list',
    type: 'react',
    category: 'advanced',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'kanban-board',
    title: 'Kanban board',
    description: 'Build a Kanban board with drag and drop',
    type: 'react',
    category: 'advanced',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'chat-ui',
    title: 'Chat UI',
    description: 'Create a chat interface with message bubbles',
    type: 'react',
    category: 'advanced',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'autocomplete',
    title: 'Autocomplete input',
    description: 'Build an autocomplete input with suggestions',
    type: 'react',
    category: 'advanced',
    difficulty: 'hard',
    component: Placeholder,
  },

  // Real-world
  {
    id: 'otp-input',
    title: 'OTP input',
    description: 'Create an OTP input component with auto-focus',
    type: 'react',
    category: 'real-world',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'countdown-timer',
    title: 'Countdown timer',
    description: 'Build a countdown timer component',
    type: 'react',
    category: 'real-world',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'rating',
    title: 'Rating component',
    description: 'Create a star rating component',
    type: 'react',
    category: 'real-world',
    difficulty: 'easy',
    component: Placeholder,
  },
  {
    id: 'breadcrumb',
    title: 'Breadcrumb navigation',
    description: 'Implement breadcrumb navigation',
    type: 'react',
    category: 'real-world',
    difficulty: 'easy',
    component: Placeholder,
  },
  {
    id: 'password-strength',
    title: 'Password strength checker',
    description: 'Build a password strength indicator',
    type: 'react',
    category: 'real-world',
    difficulty: 'medium',
    component: Placeholder,
  },

  // Architecture-level
  {
    id: 'feature-flags',
    title: 'Feature flag system',
    description: 'Create a feature flag system with context',
    type: 'react',
    category: 'architecture',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'role-based-ui',
    title: 'Role-based UI rendering',
    description: 'Implement role-based component rendering',
    type: 'react',
    category: 'architecture',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'error-boundary',
    title: 'Error boundary implementation',
    description: 'Create a reusable error boundary component',
    type: 'react',
    category: 'architecture',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'retry-api',
    title: 'Retry API mechanism (mock)',
    description: 'Build a retry mechanism for API calls',
    type: 'react',
    category: 'architecture',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'event-bus',
    title: 'Global event bus',
    description: 'Create a global event bus for component communication',
    type: 'react',
    category: 'architecture',
    difficulty: 'hard',
    component: Placeholder,
  },

  // Bonus (Standout)
  {
    id: 'form-builder',
    title: 'Form builder',
    description: 'Build a dynamic form builder',
    type: 'react',
    category: 'bonus',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'json-viewer',
    title: 'JSON viewer',
    description: 'Create a JSON viewer with expand/collapse',
    type: 'react',
    category: 'bonus',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'code-editor-wrapper',
    title: 'Code editor wrapper',
    description: 'Build a code editor wrapper with syntax highlighting',
    type: 'react',
    category: 'bonus',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'notification-center',
    title: 'Notification center',
    description: 'Create a notification center with real-time updates',
    type: 'react',
    category: 'bonus',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'dashboard-layout',
    title: 'Dashboard layout system',
    description: 'Build a responsive dashboard layout system',
    type: 'react',
    category: 'bonus',
    difficulty: 'hard',
    component: Placeholder,
  },

  // JavaScript Questions
  {
    id: 'debounce-js',
    title: 'Debounce Implementation',
    description: 'Implement a debounce function that delays invoking a function until after wait milli-seconds have elapsed since the last time the debounced function was invoked.',
    type: 'javascript',
    category: 'utility',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'throttle-js',
    title: 'Throttle Implementation',
    description: 'Implement a throttle function that only invokes the original function at most once per every wait milliseconds.',
    type: 'javascript',
    category: 'utility',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'array-map-polyfill',
    title: 'Array.prototype.map Polyfill',
    description: 'Implement your own version of Array.prototype.map.',
    type: 'javascript',
    category: 'polyfill',
    difficulty: 'easy',
    component: Placeholder,
  },
  {
    id: 'curry-implementation',
    title: 'Currying Implementation',
    description: 'Implement a function that takes a function and returns a curried version of that function.',
    type: 'javascript',
    category: 'utility',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'deep-clone',
    title: 'Deep Clone Utility',
    description: 'Implement a function that performs a deep clone of an object.',
    type: 'javascript',
    category: 'utility',
    difficulty: 'medium',
    component: Placeholder,
  },
  {
    id: 'promise-all-polyfill',
    title: 'Promise.all Polyfill',
    description: 'Implement a custom version of Promise.all that takes an array of promises and returns a single promise.',
    type: 'javascript',
    category: 'polyfill',
    difficulty: 'hard',
    component: Placeholder,
  },
  {
    id: 'flatten-array',
    title: 'Flatten Array',
    description: 'Implement a function to flatten a nested array to a single level.',
    type: 'javascript',
    category: 'algorithm',
    difficulty: 'easy',
    component: Placeholder,
  },
  {
    id: 'memoize-utility',
    title: 'Memoize Function',
    description: 'Create a memoization function that caches results of expensive function calls.',
    type: 'javascript',
    category: 'utility',
    difficulty: 'medium',
    component: Placeholder,
  }
];
